let arr :any[] = [12, 45, `sksmdfkm`, 0.234, {age: 25}, 76, undefined, null, [21, 45, 13], NaN]
console.log(arr[0])
console.log(arr[1])
console.log(arr[2])
console.log(arr[3])
console.log(arr[4])
console.log(arr[5])
console.log(arr[6])
console.log(arr[7])
console.log(arr[8])
console.log(arr[9])